# Mac Data Engineering Setup - Shell Customizations
# Auto-generated by setup.sh

# SnowSQL PATH
export PATH=/Applications/SnowSQL.app/Contents/MacOS:$PATH

# AWS CloudFormation LSP fix alias
alias fix-aws-cf-lsp="rm -rf \"$HOME/Library/Application Support/aws-cloudformation-languageserver/lmdb/\" && echo \"AWS CF language server cache cleared - restart VS Code\""
